import { describe, expect, it } from 'vitest'
import { calculateAvailableStock } from '@/lib/composedProductStock'

describe('calculateAvailableStock', () => {
  const rawMaterials = [
    { id: 'rm-flour', currentStock: 10 },
    { id: 'rm-cheese', currentStock: 6 },
  ] as any

  it('supports canonical rawMaterialId ingredients', () => {
    const recipe = {
      ingredients: [
        { rawMaterialId: 'rm-flour', quantity: 2 },
        { rawMaterialId: 'rm-cheese', quantity: 3 },
      ],
    } as any

    expect(calculateAvailableStock(recipe, rawMaterials)).toBe(2)
  })

  it('supports legacy materialId ingredients', () => {
    const recipe = {
      ingredients: [
        { materialId: 'rm-flour', quantity: 2 },
        { materialId: 'rm-cheese', quantity: 3 },
      ],
    } as any

    expect(calculateAvailableStock(recipe, rawMaterials)).toBe(2)
  })

  it('supports materials arrays generated by composed products flow', () => {
    const recipe = {
      materials: [
        { materialId: 'rm-flour', quantity: 5 },
      ],
    } as any

    expect(calculateAvailableStock(recipe, rawMaterials)).toBe(2)
  })
})
