#!/usr/bin/env node
/**
 * Import Lebanese PCG chart from Excel → generated TS module (vendor + functions).
 *
 *   node scripts/importLebanesePcgFromExcel.cjs
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const repoRoot = path.resolve(__dirname, '..');
const xlsxPath = path.join(repoRoot, 'the eco sys', 'Chart of Accounts.xlsx');

if (!fs.existsSync(xlsxPath)) {
  console.error('❌ Missing:', xlsxPath);
  process.exit(1);
}

function parseXlsxRows(filePath) {
  const pyScript = path.join(__dirname, 'parseCoaXlsx.py');
  const out = execSync(`python3 "${pyScript}" "${filePath}"`, {
    encoding: 'utf8',
    maxBuffer: 10 * 1024 * 1024,
  });
  return JSON.parse(out);
}

/** HD→G, D→D, C→C, N.A→NA, etc. */
function mapKind(raw) {
  const k = String(raw || '').trim().toUpperCase();
  if (k === 'HD') return 'G';
  if (k === 'D') return 'D';
  if (k === 'C') return 'C';
  if (k === 'N.A' || k === 'NA') return 'NA';
  if (k === 'C=D' || k === 'C/D') return 'CD';
  return k || 'D';
}

function inferParentCode(code, byCode) {
  let best = '';
  for (const candidate of Object.keys(byCode)) {
    if (candidate === code) continue;
    if (!code.startsWith(candidate)) continue;
    if (candidate.length <= best.length) continue;
    const row = byCode[candidate];
    if (row.kind === 'G' || row.rawKind === 'HD') {
      best = candidate;
    }
  }
  return best || undefined;
}

function buildChart(rows) {
  const dataRows = rows.slice(1).filter((r) => r[0] && /^\d/.test(String(r[0])));
  const byCode = {};
  for (const r of dataRows) {
    const code = String(r[0]).trim();
    byCode[code] = {
      code,
      name: String(r[1] || '').trim(),
      rawKind: String(r[2] || '').trim(),
      kind: mapKind(r[2]),
      nameAr: String(r[3] || '').trim(),
      currency: 'LL',
    };
  }
  for (const row of Object.values(byCode)) {
    row.parentCode = inferParentCode(row.code, byCode);
  }
  return Object.values(byCode).sort((a, b) => a.code.localeCompare(b.code, undefined, { numeric: true }));
}

function emitTs(chart, outPath) {
  const header = `/** Auto-generated by scripts/importLebanesePcgFromExcel.cjs — do not edit manually. */
export type PcgAccountKind = 'G' | 'D' | 'C' | 'NA' | 'CD';

export type LebanesePcgAccount = {
  code: string;
  name: string;
  nameAr: string;
  kind: PcgAccountKind;
  rawKind: string;
  currency: 'LL' | 'USD';
  parentCode?: string;
};

export const LEBANESE_PCG_CHART: LebanesePcgAccount[] = `;
  const body = JSON.stringify(chart, null, 2);
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, `${header}${body};\n`);
}

const rows = parseXlsxRows(xlsxPath);
const chart = buildChart(rows);

const targets = [
  path.join(repoRoot, 'vendor/beirut-finance-flow-main/src/lib/ledger/lebanesePcgChart.generated.ts'),
  path.join(repoRoot, 'functions/src/lib/ledger/lebanesePcgChart.generated.ts'),
];

for (const t of targets) {
  emitTs(chart, t);
  console.log('✅ Wrote', t);
}

console.log(`   ${chart.length} PCG accounts (G: ${chart.filter((c) => c.kind === 'G').length}, D: ${chart.filter((c) => c.kind === 'D').length}, C: ${chart.filter((c) => c.kind === 'C').length})`);
